spring:
  datasource:
    url: jdbc:mysql://localhost:3306/juntai?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: wyfnb666
server:
  port: 8090

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.edu.guet.weappdemo.bean

